config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'tasks/:id', to: 'tasks#update'
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end


  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<div class="container">

  <h1>My tasks</h1>


  <ul class="list">
    <% @tasks.each do |task| %>
      <% done = task.completed  %>
      <div class="items">
        <% if done %>
          <i class="far fa-check-square"></i>
        <% else %>
          <i class="far fa-square"></i>
        <% end  %>
        <li class="label"><%=link_to "#{task.title}", task_path(task) %></li>
        <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe,
         task_path(task),
         {method: :delete,
         data: { confirm: "Are you sure to destroy #{task.title}?" }} %>

      </div>
    <% end %>
  </ul>

  <p>
    <i style="color:rgb(52, 152, 220)" class="fas fa-plus"></i>
    <%= link_to "Add a new task", tasks_new_path %>
  </p>

</div>


<!-- <ul class="list">
  <% @tasks.each do |task| %>
      <% done = task.completed ? "checked" : "" %>
      <div class="items">
        <input type="checkbox" id="<%task.id %>" name="<%task.title %>"
               <%= done %>>
        <label for="<%task.id %>"><li><%= task.title %></li></label>
      </div>
    <% end %>
</ul> -->

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<div class="container">
  <h1><%= @task.title %></h1>

  <div class="uptate">
    <%= link_to "Update this task", task_edit_path %>
  </div>

  <div class="detail">
    <%= @task.details %>
  </div>
  <div style="margin-top: 20px;" >
    <% if @task.completed %>
      <i class="far fa-check-square"></i>
      <span>"This task is completed!</span>
    <%else%>
      <i class="far fa-square"></i>
      <span>"This task is not completed yet</span>
    <% end %>
  </div>

  <%= link_to "Back to list", tasks_path %>

</div>